permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown

# 作者信息
author: 
  name: D.K.
  email: 453523830@qq.com 
  link: http://darklost.me
  github: http://github.com/darklost
  music: http://user.qzone.qq.com/453523830/305


# 站点信息
title: D.K.的博客
description: My personal blog
url: http://darklost.me
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/img_logo.png
favicon: /public/img/img_logo.png


# 主题设置，自动激活某个标签
active: 游戏开发

# 首页除了最新文章外显示分类
cates: 
  - Cocos2d-x
  - Android

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
#gems
gems: [jekyll-paginate]